update name checking to find typos too

diff --git a/subtree b/subtree
--- a/subtree
+++ b/subtree
@@ -38,6 +38,12 @@ function check_name() {
     help
     exit 1
   fi
+  if [ ! ${REMOTES[$2]+_} ]; then
+    echo "ERROR: $2 is not a known remote"
+    echo ""
+    help
+    exit 1
+  fi
 }
 
 case "$1" in
@@ -63,6 +69,7 @@ case "$1" in
 
   # initialize a subtree from an existing remote
   init)
+    check_name $*
     git subtree add --prefix=$2 ${@:2} master
     ;;
 
